### PR TITLE
More refactoring and whatnot.

### PR DESCRIPTION
**Pull request by samwho**
Lots more changes, mostly structural this time. Tried to decompose the code into classes that make sense. I feel like it's cleaner as a result.

No joy on getting more performance out of it, other than faster start up by estimating the number of frames instead of counting them. We only used that number for progress anyway, and it doesn't matter if that's an estimate.

On the subject of progress, actually put a real progress bar in there now. Nice little finishing touch. :)

I'm not sure where the next big win would come from in terms of performance. You could get fancy and try to do some GPU coding.

Or, if that's daunting, you might be able to squeeze some performance out by using more CPU cores. This will probably require forking new processes, Python doesn't typically do a good job of utilising more cores with threads. I took a swing at this but had a bit of difficulty. It's probably doable, though.

### CODE REVIEW

**Comment by jakemalachowski** [comment]
What version of Python are you running?  I am running 3.6 and am getting an error with the ProgressBar.  I looked it up and it says that some of the ProgressBar functionality isn't compatible with Python 3.

**Comment by samwho** [comment]
Ah, I'm running 2.7.

**Comment by jakemalachowski** [comment]
Do you think that's something we should take out then? I feel like a lot of people are going to be using Python 3 and won't be able to run the program.  There is probably some other progress bar that works with Python 3.

**Comment by samwho** [comment]
Check for a Python 3 version of this one. There probably is one. If there isn't, yeah, probably best to take it out.

**Comment by jakemalachowski** [comment]
I'll look into it in a couple hours.

**Comment by jakemalachowski** [comment]
I believe that I got the ProgressBar issue figured out, but I am now getting an OutOfMemory error (With 8 GB of free RAM at the time of running)  The area points here:

  File "C:\s\VideoColorAnalyzer\videoparser\video.py", line 100, in _spawn
    bufsize=self.bytes_per_frame * 300)
  File "C:\Python\Python36-32\lib\subprocess.py", line 691, in __init__
    self.stdout = io.open(c2pread, 'rb', bufsize)

So I'm guessing it's creating a giant buffer that my computer (and I'm sure most other peoples') can't handle.  I'm looking into it, but I thought I would let you know that I am still working on this.

**Comment by samwho** [comment]
Very reasonable guess.

I'd check my functions that get the width and height. I think that's likely where the problem is, and is resulting in bytes_per_frame being erroneously huge.

**Comment by samwho** [comment]
Added a new commit that vastly improves speed once again. Explanation in the commit message. This is fun. :)

**Comment by jakemalachowski** [comment]
Dude this is really impressive.  Awesome work.  I'm running it right now and as long as it finishes without issues I'll merge.

**Pull request merged**
